# Inverter App

services:
  inverter:
    build: .
    container_name: inverter
    restart: unless-stopped
    env_file: ./.env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.inverter.rule=Host(`solar.bespokeaistudios.online`)"
      - "traefik.http.routers.inverter.entrypoints=https"
      - "traefik.http.routers.inverter.tls.certresolver=letsencrypt"
      - "traefik.http.services.inverter.loadbalancer.server.port=3000"
    networks:
      - proxy
      - backend

networks:
  proxy:
    external: true
  backend:
    external: true
